### PR TITLE
Updated whatsApp & Android-SDK issues

### PR DESCRIPTION
**Pull request by YuvrajRaghuvanshiS**
Updated Whatsapp with link file and new apk files which works.
android_sdk.py modified to solve many issues regarding downloading of SDK.

Solved : #51 #47 #41 #40 #35 and many more.

### CODE REVIEW

**Comment by HonzaSTECH** [comment]
After I downloaded your master branch, I got much further than with the base version, but it still won't let me install the SDK completely.

There is some problem with accepting licences, I don't have a chance to type `y` and the licences probably reject themselves, one by one. In the end, I get:
```
[ERROR] Could not install packages from SDK Manager
[ERROR] Failed to install Android SDK
```

So I tried running the same command again. The output looked similar, but it took a bit longer. To the end, there was a prompt:
```
Do you wish to create a custom hardware profile [no]
```
but I couldn't type anything. After a minute or two, it just wrote
```
Android AVD successfully installed.
```

I hope it will work now. But is this the expected behaviour?

**Comment by yuvrajraghuvanshis** [comment]
Allow me some time to look into that.

**Comment by HonzaSTECH** [comment]
Update: It works (the installation of SVK)!
You're a legend.
Somebody (@MarcoG3), please merge this.

**Comment by yuvrajraghuvanshis** [comment]
Thanks.
Can you comment what did you miss the first time? Most of the times others benefit from it.

**Comment by HonzaSTECH** [comment]
I don't think I really missed anything. I just had to run the same command twice and then the emulator was installed successfully.

**Comment by guanana** [comment]
Thanks for the pull, I have still a problem with your code. When running on MacOS High Sierra

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli : Unsupported major.minor version 52.0`

**Comment by YuvrajRaghuvanshiS** [comment]
Hi @guanana , looks like you fixed it. I have not worked with this for a while that's why these issues are still here.

**Comment by YuvrajRaghuvanshiS** [comment]
Hey whoever reading this message.
I am no longer maintaining/ working on this fork however "अतिथिदेवो भव:" : Guests are equivalent to God. And I will not leave you empty handed. Here is what you can try which I wrote.
https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor

**Review by rschuppan — APPROVED** [review]
OMG pleeease update with those changes

**Review by HonzaSTECH — APPROVED** [review]

**Pull request merged**
